- op: add
  path: /spec/template/spec/containers/0/args/-
  value: -oauth-issuer=http://uptime-app.uptime.svc.cluster.local
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: -resource-url=https://mcp.sandbox.upeks.net
