// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tools

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	uptime0 "github.com/uptime-com/uptime-client-go"
	"github.com/uptime-com/uptime-mcp/internal/uptime"
)

// newClientMock creates a new instance of clientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *clientMock {
	mock := &clientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// clientMock is an autogenerated mock type for the mockeryClient type
type clientMock struct {
	mock.Mock
}

type clientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *clientMock) EXPECT() *clientMock_Expecter {
	return &clientMock_Expecter{mock: &_m.Mock}
}

// Checks provides a mock function for the type clientMock
func (_mock *clientMock) Checks() uptime.ChecksService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Checks")
	}

	var r0 uptime.ChecksService
	if returnFunc, ok := ret.Get(0).(func() uptime.ChecksService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uptime.ChecksService)
		}
	}
	return r0
}

// clientMock_Checks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checks'
type clientMock_Checks_Call struct {
	*mock.Call
}

// Checks is a helper method to define mock.On call
func (_e *clientMock_Expecter) Checks() *clientMock_Checks_Call {
	return &clientMock_Checks_Call{Call: _e.mock.On("Checks")}
}

func (_c *clientMock_Checks_Call) Run(run func()) *clientMock_Checks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *clientMock_Checks_Call) Return(checksService uptime.ChecksService) *clientMock_Checks_Call {
	_c.Call.Return(checksService)
	return _c
}

func (_c *clientMock_Checks_Call) RunAndReturn(run func() uptime.ChecksService) *clientMock_Checks_Call {
	_c.Call.Return(run)
	return _c
}

// Outages provides a mock function for the type clientMock
func (_mock *clientMock) Outages() uptime.OutagesService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Outages")
	}

	var r0 uptime.OutagesService
	if returnFunc, ok := ret.Get(0).(func() uptime.OutagesService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uptime.OutagesService)
		}
	}
	return r0
}

// clientMock_Outages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Outages'
type clientMock_Outages_Call struct {
	*mock.Call
}

// Outages is a helper method to define mock.On call
func (_e *clientMock_Expecter) Outages() *clientMock_Outages_Call {
	return &clientMock_Outages_Call{Call: _e.mock.On("Outages")}
}

func (_c *clientMock_Outages_Call) Run(run func()) *clientMock_Outages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *clientMock_Outages_Call) Return(outagesService uptime.OutagesService) *clientMock_Outages_Call {
	_c.Call.Return(outagesService)
	return _c
}

func (_c *clientMock_Outages_Call) RunAndReturn(run func() uptime.OutagesService) *clientMock_Outages_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function for the type clientMock
func (_mock *clientMock) Tags() uptime.TagsService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 uptime.TagsService
	if returnFunc, ok := ret.Get(0).(func() uptime.TagsService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uptime.TagsService)
		}
	}
	return r0
}

// clientMock_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type clientMock_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
func (_e *clientMock_Expecter) Tags() *clientMock_Tags_Call {
	return &clientMock_Tags_Call{Call: _e.mock.On("Tags")}
}

func (_c *clientMock_Tags_Call) Run(run func()) *clientMock_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *clientMock_Tags_Call) Return(tagsService uptime.TagsService) *clientMock_Tags_Call {
	_c.Call.Return(tagsService)
	return _c
}

func (_c *clientMock_Tags_Call) RunAndReturn(run func() uptime.TagsService) *clientMock_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// newChecksServiceMock creates a new instance of checksServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newChecksServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *checksServiceMock {
	mock := &checksServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// checksServiceMock is an autogenerated mock type for the mockeryChecksService type
type checksServiceMock struct {
	mock.Mock
}

type checksServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *checksServiceMock) EXPECT() *checksServiceMock_Expecter {
	return &checksServiceMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type checksServiceMock
func (_mock *checksServiceMock) Create(ctx context.Context, check *uptime0.Check) (*uptime0.Check, *http.Response, error) {
	ret := _mock.Called(ctx, check)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *uptime0.Check
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Check) (*uptime0.Check, *http.Response, error)); ok {
		return returnFunc(ctx, check)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Check) *uptime0.Check); ok {
		r0 = returnFunc(ctx, check)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Check)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.Check) *http.Response); ok {
		r1 = returnFunc(ctx, check)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.Check) error); ok {
		r2 = returnFunc(ctx, check)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// checksServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type checksServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - check *uptime0.Check
func (_e *checksServiceMock_Expecter) Create(ctx interface{}, check interface{}) *checksServiceMock_Create_Call {
	return &checksServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, check)}
}

func (_c *checksServiceMock_Create_Call) Run(run func(ctx context.Context, check *uptime0.Check)) *checksServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.Check
		if args[1] != nil {
			arg1 = args[1].(*uptime0.Check)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *checksServiceMock_Create_Call) Return(check1 *uptime0.Check, response *http.Response, err error) *checksServiceMock_Create_Call {
	_c.Call.Return(check1, response, err)
	return _c
}

func (_c *checksServiceMock_Create_Call) RunAndReturn(run func(ctx context.Context, check *uptime0.Check) (*uptime0.Check, *http.Response, error)) *checksServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type checksServiceMock
func (_mock *checksServiceMock) Delete(ctx context.Context, pk int) (*http.Response, error) {
	ret := _mock.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*http.Response, error)); ok {
		return returnFunc(ctx, pk)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *http.Response); ok {
		r0 = returnFunc(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, pk)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// checksServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type checksServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - pk int
func (_e *checksServiceMock_Expecter) Delete(ctx interface{}, pk interface{}) *checksServiceMock_Delete_Call {
	return &checksServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, pk)}
}

func (_c *checksServiceMock_Delete_Call) Run(run func(ctx context.Context, pk int)) *checksServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *checksServiceMock_Delete_Call) Return(response *http.Response, err error) *checksServiceMock_Delete_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *checksServiceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, pk int) (*http.Response, error)) *checksServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type checksServiceMock
func (_mock *checksServiceMock) Get(ctx context.Context, pk int) (*uptime0.Check, *http.Response, error) {
	ret := _mock.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *uptime0.Check
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*uptime0.Check, *http.Response, error)); ok {
		return returnFunc(ctx, pk)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *uptime0.Check); ok {
		r0 = returnFunc(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Check)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) *http.Response); ok {
		r1 = returnFunc(ctx, pk)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, pk)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// checksServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type checksServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - pk int
func (_e *checksServiceMock_Expecter) Get(ctx interface{}, pk interface{}) *checksServiceMock_Get_Call {
	return &checksServiceMock_Get_Call{Call: _e.mock.On("Get", ctx, pk)}
}

func (_c *checksServiceMock_Get_Call) Run(run func(ctx context.Context, pk int)) *checksServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *checksServiceMock_Get_Call) Return(check *uptime0.Check, response *http.Response, err error) *checksServiceMock_Get_Call {
	_c.Call.Return(check, response, err)
	return _c
}

func (_c *checksServiceMock_Get_Call) RunAndReturn(run func(ctx context.Context, pk int) (*uptime0.Check, *http.Response, error)) *checksServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type checksServiceMock
func (_mock *checksServiceMock) List(ctx context.Context, opt *uptime0.CheckListOptions) ([]*uptime0.Check, *http.Response, error) {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*uptime0.Check
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.CheckListOptions) ([]*uptime0.Check, *http.Response, error)); ok {
		return returnFunc(ctx, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.CheckListOptions) []*uptime0.Check); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*uptime0.Check)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.CheckListOptions) *http.Response); ok {
		r1 = returnFunc(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.CheckListOptions) error); ok {
		r2 = returnFunc(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// checksServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type checksServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *uptime0.CheckListOptions
func (_e *checksServiceMock_Expecter) List(ctx interface{}, opt interface{}) *checksServiceMock_List_Call {
	return &checksServiceMock_List_Call{Call: _e.mock.On("List", ctx, opt)}
}

func (_c *checksServiceMock_List_Call) Run(run func(ctx context.Context, opt *uptime0.CheckListOptions)) *checksServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.CheckListOptions
		if args[1] != nil {
			arg1 = args[1].(*uptime0.CheckListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *checksServiceMock_List_Call) Return(checks []*uptime0.Check, response *http.Response, err error) *checksServiceMock_List_Call {
	_c.Call.Return(checks, response, err)
	return _c
}

func (_c *checksServiceMock_List_Call) RunAndReturn(run func(ctx context.Context, opt *uptime0.CheckListOptions) ([]*uptime0.Check, *http.Response, error)) *checksServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type checksServiceMock
func (_mock *checksServiceMock) Stats(ctx context.Context, pk int, opt *uptime0.CheckStatsOptions) (*uptime0.CheckStatsResponse, *http.Response, error) {
	ret := _mock.Called(ctx, pk, opt)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 *uptime0.CheckStatsResponse
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *uptime0.CheckStatsOptions) (*uptime0.CheckStatsResponse, *http.Response, error)); ok {
		return returnFunc(ctx, pk, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *uptime0.CheckStatsOptions) *uptime0.CheckStatsResponse); ok {
		r0 = returnFunc(ctx, pk, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.CheckStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *uptime0.CheckStatsOptions) *http.Response); ok {
		r1 = returnFunc(ctx, pk, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, *uptime0.CheckStatsOptions) error); ok {
		r2 = returnFunc(ctx, pk, opt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// checksServiceMock_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type checksServiceMock_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
//   - pk int
//   - opt *uptime0.CheckStatsOptions
func (_e *checksServiceMock_Expecter) Stats(ctx interface{}, pk interface{}, opt interface{}) *checksServiceMock_Stats_Call {
	return &checksServiceMock_Stats_Call{Call: _e.mock.On("Stats", ctx, pk, opt)}
}

func (_c *checksServiceMock_Stats_Call) Run(run func(ctx context.Context, pk int, opt *uptime0.CheckStatsOptions)) *checksServiceMock_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *uptime0.CheckStatsOptions
		if args[2] != nil {
			arg2 = args[2].(*uptime0.CheckStatsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *checksServiceMock_Stats_Call) Return(checkStatsResponse *uptime0.CheckStatsResponse, response *http.Response, err error) *checksServiceMock_Stats_Call {
	_c.Call.Return(checkStatsResponse, response, err)
	return _c
}

func (_c *checksServiceMock_Stats_Call) RunAndReturn(run func(ctx context.Context, pk int, opt *uptime0.CheckStatsOptions) (*uptime0.CheckStatsResponse, *http.Response, error)) *checksServiceMock_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type checksServiceMock
func (_mock *checksServiceMock) Update(ctx context.Context, check *uptime0.Check) (*uptime0.Check, *http.Response, error) {
	ret := _mock.Called(ctx, check)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *uptime0.Check
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Check) (*uptime0.Check, *http.Response, error)); ok {
		return returnFunc(ctx, check)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Check) *uptime0.Check); ok {
		r0 = returnFunc(ctx, check)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Check)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.Check) *http.Response); ok {
		r1 = returnFunc(ctx, check)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.Check) error); ok {
		r2 = returnFunc(ctx, check)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// checksServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type checksServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - check *uptime0.Check
func (_e *checksServiceMock_Expecter) Update(ctx interface{}, check interface{}) *checksServiceMock_Update_Call {
	return &checksServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, check)}
}

func (_c *checksServiceMock_Update_Call) Run(run func(ctx context.Context, check *uptime0.Check)) *checksServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.Check
		if args[1] != nil {
			arg1 = args[1].(*uptime0.Check)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *checksServiceMock_Update_Call) Return(check1 *uptime0.Check, response *http.Response, err error) *checksServiceMock_Update_Call {
	_c.Call.Return(check1, response, err)
	return _c
}

func (_c *checksServiceMock_Update_Call) RunAndReturn(run func(ctx context.Context, check *uptime0.Check) (*uptime0.Check, *http.Response, error)) *checksServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newTagsServiceMock creates a new instance of tagsServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTagsServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *tagsServiceMock {
	mock := &tagsServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// tagsServiceMock is an autogenerated mock type for the mockeryTagsService type
type tagsServiceMock struct {
	mock.Mock
}

type tagsServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *tagsServiceMock) EXPECT() *tagsServiceMock_Expecter {
	return &tagsServiceMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type tagsServiceMock
func (_mock *tagsServiceMock) Create(ctx context.Context, tag *uptime0.Tag) (*uptime0.Tag, *http.Response, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *uptime0.Tag
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Tag) (*uptime0.Tag, *http.Response, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Tag) *uptime0.Tag); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.Tag) *http.Response); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.Tag) error); ok {
		r2 = returnFunc(ctx, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// tagsServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type tagsServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *uptime0.Tag
func (_e *tagsServiceMock_Expecter) Create(ctx interface{}, tag interface{}) *tagsServiceMock_Create_Call {
	return &tagsServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, tag)}
}

func (_c *tagsServiceMock_Create_Call) Run(run func(ctx context.Context, tag *uptime0.Tag)) *tagsServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.Tag
		if args[1] != nil {
			arg1 = args[1].(*uptime0.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *tagsServiceMock_Create_Call) Return(tag1 *uptime0.Tag, response *http.Response, err error) *tagsServiceMock_Create_Call {
	_c.Call.Return(tag1, response, err)
	return _c
}

func (_c *tagsServiceMock_Create_Call) RunAndReturn(run func(ctx context.Context, tag *uptime0.Tag) (*uptime0.Tag, *http.Response, error)) *tagsServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type tagsServiceMock
func (_mock *tagsServiceMock) Delete(ctx context.Context, pk int) (*http.Response, error) {
	ret := _mock.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*http.Response, error)); ok {
		return returnFunc(ctx, pk)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *http.Response); ok {
		r0 = returnFunc(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, pk)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// tagsServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type tagsServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - pk int
func (_e *tagsServiceMock_Expecter) Delete(ctx interface{}, pk interface{}) *tagsServiceMock_Delete_Call {
	return &tagsServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, pk)}
}

func (_c *tagsServiceMock_Delete_Call) Run(run func(ctx context.Context, pk int)) *tagsServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *tagsServiceMock_Delete_Call) Return(response *http.Response, err error) *tagsServiceMock_Delete_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *tagsServiceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, pk int) (*http.Response, error)) *tagsServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type tagsServiceMock
func (_mock *tagsServiceMock) Get(ctx context.Context, pk int) (*uptime0.Tag, *http.Response, error) {
	ret := _mock.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *uptime0.Tag
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*uptime0.Tag, *http.Response, error)); ok {
		return returnFunc(ctx, pk)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *uptime0.Tag); ok {
		r0 = returnFunc(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) *http.Response); ok {
		r1 = returnFunc(ctx, pk)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, pk)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// tagsServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type tagsServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - pk int
func (_e *tagsServiceMock_Expecter) Get(ctx interface{}, pk interface{}) *tagsServiceMock_Get_Call {
	return &tagsServiceMock_Get_Call{Call: _e.mock.On("Get", ctx, pk)}
}

func (_c *tagsServiceMock_Get_Call) Run(run func(ctx context.Context, pk int)) *tagsServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *tagsServiceMock_Get_Call) Return(tag *uptime0.Tag, response *http.Response, err error) *tagsServiceMock_Get_Call {
	_c.Call.Return(tag, response, err)
	return _c
}

func (_c *tagsServiceMock_Get_Call) RunAndReturn(run func(ctx context.Context, pk int) (*uptime0.Tag, *http.Response, error)) *tagsServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type tagsServiceMock
func (_mock *tagsServiceMock) List(ctx context.Context, opt *uptime0.TagListOptions) ([]*uptime0.Tag, *http.Response, error) {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*uptime0.Tag
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.TagListOptions) ([]*uptime0.Tag, *http.Response, error)); ok {
		return returnFunc(ctx, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.TagListOptions) []*uptime0.Tag); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*uptime0.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.TagListOptions) *http.Response); ok {
		r1 = returnFunc(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.TagListOptions) error); ok {
		r2 = returnFunc(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// tagsServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type tagsServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *uptime0.TagListOptions
func (_e *tagsServiceMock_Expecter) List(ctx interface{}, opt interface{}) *tagsServiceMock_List_Call {
	return &tagsServiceMock_List_Call{Call: _e.mock.On("List", ctx, opt)}
}

func (_c *tagsServiceMock_List_Call) Run(run func(ctx context.Context, opt *uptime0.TagListOptions)) *tagsServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.TagListOptions
		if args[1] != nil {
			arg1 = args[1].(*uptime0.TagListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *tagsServiceMock_List_Call) Return(tags []*uptime0.Tag, response *http.Response, err error) *tagsServiceMock_List_Call {
	_c.Call.Return(tags, response, err)
	return _c
}

func (_c *tagsServiceMock_List_Call) RunAndReturn(run func(ctx context.Context, opt *uptime0.TagListOptions) ([]*uptime0.Tag, *http.Response, error)) *tagsServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type tagsServiceMock
func (_mock *tagsServiceMock) Update(ctx context.Context, tag *uptime0.Tag) (*uptime0.Tag, *http.Response, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *uptime0.Tag
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Tag) (*uptime0.Tag, *http.Response, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.Tag) *uptime0.Tag); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.Tag) *http.Response); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.Tag) error); ok {
		r2 = returnFunc(ctx, tag)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// tagsServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type tagsServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *uptime0.Tag
func (_e *tagsServiceMock_Expecter) Update(ctx interface{}, tag interface{}) *tagsServiceMock_Update_Call {
	return &tagsServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, tag)}
}

func (_c *tagsServiceMock_Update_Call) Run(run func(ctx context.Context, tag *uptime0.Tag)) *tagsServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.Tag
		if args[1] != nil {
			arg1 = args[1].(*uptime0.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *tagsServiceMock_Update_Call) Return(tag1 *uptime0.Tag, response *http.Response, err error) *tagsServiceMock_Update_Call {
	_c.Call.Return(tag1, response, err)
	return _c
}

func (_c *tagsServiceMock_Update_Call) RunAndReturn(run func(ctx context.Context, tag *uptime0.Tag) (*uptime0.Tag, *http.Response, error)) *tagsServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newOutagesServiceMock creates a new instance of outagesServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOutagesServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *outagesServiceMock {
	mock := &outagesServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// outagesServiceMock is an autogenerated mock type for the mockeryOutagesService type
type outagesServiceMock struct {
	mock.Mock
}

type outagesServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *outagesServiceMock) EXPECT() *outagesServiceMock_Expecter {
	return &outagesServiceMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type outagesServiceMock
func (_mock *outagesServiceMock) Get(ctx context.Context, pk string) (*uptime0.Outage, *http.Response, error) {
	ret := _mock.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *uptime0.Outage
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*uptime0.Outage, *http.Response, error)); ok {
		return returnFunc(ctx, pk)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *uptime0.Outage); ok {
		r0 = returnFunc(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uptime0.Outage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = returnFunc(ctx, pk)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, pk)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// outagesServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type outagesServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
func (_e *outagesServiceMock_Expecter) Get(ctx interface{}, pk interface{}) *outagesServiceMock_Get_Call {
	return &outagesServiceMock_Get_Call{Call: _e.mock.On("Get", ctx, pk)}
}

func (_c *outagesServiceMock_Get_Call) Run(run func(ctx context.Context, pk string)) *outagesServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *outagesServiceMock_Get_Call) Return(outage *uptime0.Outage, response *http.Response, err error) *outagesServiceMock_Get_Call {
	_c.Call.Return(outage, response, err)
	return _c
}

func (_c *outagesServiceMock_Get_Call) RunAndReturn(run func(ctx context.Context, pk string) (*uptime0.Outage, *http.Response, error)) *outagesServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type outagesServiceMock
func (_mock *outagesServiceMock) List(ctx context.Context, opt *uptime0.OutageListOptions) ([]*uptime0.Outage, *http.Response, error) {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*uptime0.Outage
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.OutageListOptions) ([]*uptime0.Outage, *http.Response, error)); ok {
		return returnFunc(ctx, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uptime0.OutageListOptions) []*uptime0.Outage); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*uptime0.Outage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uptime0.OutageListOptions) *http.Response); ok {
		r1 = returnFunc(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uptime0.OutageListOptions) error); ok {
		r2 = returnFunc(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// outagesServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type outagesServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *uptime0.OutageListOptions
func (_e *outagesServiceMock_Expecter) List(ctx interface{}, opt interface{}) *outagesServiceMock_List_Call {
	return &outagesServiceMock_List_Call{Call: _e.mock.On("List", ctx, opt)}
}

func (_c *outagesServiceMock_List_Call) Run(run func(ctx context.Context, opt *uptime0.OutageListOptions)) *outagesServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uptime0.OutageListOptions
		if args[1] != nil {
			arg1 = args[1].(*uptime0.OutageListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *outagesServiceMock_List_Call) Return(outages []*uptime0.Outage, response *http.Response, err error) *outagesServiceMock_List_Call {
	_c.Call.Return(outages, response, err)
	return _c
}

func (_c *outagesServiceMock_List_Call) RunAndReturn(run func(ctx context.Context, opt *uptime0.OutageListOptions) ([]*uptime0.Outage, *http.Response, error)) *outagesServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}
