---
name: build
run-name: 🏗️ Build ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*.*.*'
    paths-ignore:
      - deploy/**

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

jobs:

  build-images-ko:
    strategy:
      fail-fast: false
      matrix:
        package:
          - app/uptime-mcp
    uses: uptime-com/upflows/.github/workflows/build-ko.yaml@v0.17
    with:
      package: ${{ matrix.package }}
      tag: ${{ github.ref_name }}
    secrets:
      ssh_private_key: ${{ secrets.up_machine_ssh_private_key }}

  push-images:
    needs: [ build-images-ko ]
    strategy:
      fail-fast: false
      matrix:
        package:
          - app/uptime-mcp
        environment:
          - aws_region: ${{ vars.updev_aws_region }}
            aws_assume_role_arn: ${{ vars.updev_aws_assume_role_arn }}
    uses: uptime-com/upflows/.github/workflows/push-ecr.yaml@v0.16
    with:
      image: ${{ github.repository }}/${{ matrix.package }}:${{ github.ref_name }}
      aws_region: ${{ matrix.environment.aws_region }}
      aws_assume_role_arn: ${{ matrix.environment.aws_assume_role_arn }}

  bump-version:
    needs: [ push-images ]
    if: ${{ !contains(github.ref_name, '-') }}
    uses: uptime-com/upflows/.github/workflows/bump-version.yaml@v0.20
    with:
      version: ${{ github.ref_name }}
      files: |
        deploy/kustomize/overlays/upeks-dev/VERSION
      # deploy/kustomize/overlays/upeks-produs/VERSION
      # deploy/kustomize/overlays/upeks-prodeu/VERSION
    secrets:
      ssh_key: ${{ secrets.up_machine_ssh_private_key }}
