package handle

import "go.uber.org/fx"

type checksHandler struct{}

func provideChecksHandler() *checksHandler {
	return &checksHandler{}
}

var checksModule = fx.Module("tool.checks",
	fx.Provide(provideChecksHandler),
	fx.Invoke(registerListChecksTool),
	fx.Invoke(registerGetCheckTool),
	fx.Invoke(registerCheckResource),
	fx.Invoke(registerDeleteCheckTool),
	fx.Invoke(registerGetCheckStatsTool),
	fx.Invoke(registerCreateHTTPCheckTool),
	fx.Invoke(registerCreateDNSCheckTool),
	fx.Invoke(registerCreateSSLCheckTool),
	fx.Invoke(registerCreateTCPCheckTool),
	fx.Invoke(registerCreateICMPCheckTool),
	fx.Invoke(registerCreateIMAPCheckTool),
	fx.Invoke(registerCreatePOPCheckTool),
	fx.Invoke(registerCreateSMTPCheckTool),
	fx.Invoke(registerCreateUDPCheckTool),
	fx.Invoke(registerCreateNTPCheckTool),
	fx.Invoke(registerCreateSSHCheckTool),
	fx.Invoke(registerCreateHeartbeatCheckTool),
	fx.Invoke(registerCreateWebhookCheckTool),
	fx.Invoke(registerCreateWHOISCheckTool),
	fx.Invoke(registerCreateRDAPCheckTool),
	fx.Invoke(registerCreateBlacklistCheckTool),
	fx.Invoke(registerCreateMalwareCheckTool),
	fx.Invoke(registerCreateGroupCheckTool),
	fx.Invoke(registerCreatePageSpeedCheckTool),
	fx.Invoke(registerCreateRUMCheckTool),
	fx.Invoke(registerCreateRUM2CheckTool),
	fx.Invoke(registerUpdateHTTPCheckTool),
	fx.Invoke(registerUpdateDNSCheckTool),
	fx.Invoke(registerUpdateSSLCheckTool),
	fx.Invoke(registerUpdateTCPCheckTool),
	fx.Invoke(registerUpdateICMPCheckTool),
	fx.Invoke(registerUpdateIMAPCheckTool),
	fx.Invoke(registerUpdatePOPCheckTool),
	fx.Invoke(registerUpdateSMTPCheckTool),
	fx.Invoke(registerUpdateUDPCheckTool),
	fx.Invoke(registerUpdateNTPCheckTool),
	fx.Invoke(registerUpdateSSHCheckTool),
	fx.Invoke(registerUpdateHeartbeatCheckTool),
	fx.Invoke(registerUpdateWebhookCheckTool),
	fx.Invoke(registerUpdateWHOISCheckTool),
	fx.Invoke(registerUpdateRDAPCheckTool),
	fx.Invoke(registerUpdateBlacklistCheckTool),
	fx.Invoke(registerUpdateMalwareCheckTool),
	fx.Invoke(registerUpdateGroupCheckTool),
	fx.Invoke(registerUpdatePageSpeedCheckTool),
	fx.Invoke(registerUpdateRUMCheckTool),
	fx.Invoke(registerUpdateRUM2CheckTool),
	fx.Invoke(registerCreateCloudStatusCheckTool),
	fx.Invoke(registerUpdateCloudStatusCheckTool),
)
